#:schema node_modules/wrangler/config-schema.json
name = "otel-quickstart-example"
main = "src/index.ts"
compatibility_date = "2024-09-09"
compatibility_flags = [ "nodejs_compat" ]

# [vars]
# SIGNOZ_ENDPOINT = "https://ingest.{region}.signoz.cloud:443/v1/traces"
# SIGNOZ_ACCESS_TOKEN = "example"
